version: '3.8'

services:
  web:
    build: .
    container_name: speed-reporting
    ports: 
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      APP_ENV: ${APP_ENV}
      APP_URL: ${APP_URL}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}

      APACHE_DOCUMENT_ROOT: /var/www/html/public

  db:
    image: mysql:8.0
    container_name: speed-reporting-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db_data:/var/lib/mysqldocker
      - ./dev:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: speed-reporting-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    
volumes:
  db_data: